In [ ]:
!pip install ruclip==0.0.1
!pip install numpy
!pip install torch torchvision torchaudio
!pip install mkl
!apt install libomp-dev
!pip install faiss

     |████████████████████████████████| 1.7 MB 19.1 MB/s 
     |████████████████████████████████| 61 kB 331 kB/s 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libomp5
Suggested packages:
  libomp-doc
The following NEW packages will be installed:
  libomp-dev libomp5
0 upgraded, 2 newly installed, 0 to remove and 37 not upgraded.
Need to get 239 kB of archives.
After this operation, 804 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp5 amd64 5.0.1-1 [234 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp-dev amd64 5.0.1-1 [5,088 B]
Fetched 239 kB in 1s (435 kB/s)
Selecting previously unselected package libomp5:amd64.
(Reading database ... 155229 files and directories currently installed.)
Preparing to unpack .../libomp5_5.0.1-1_amd64.deb ...
Unpacking libomp5:amd64 (5.0.1-1) ...
Selecting previously un

In [ ]:
'''
  def add_vec(self):
    self.index.add(v)
'''

In [ ]:
import pickle
import faiss

class FAISS_index:

  def __init__(self, dim, param, nprobe=5):
    self.index = faiss.index_factory(dim, param)
    self.dim = dim
    self.index.nprobe = nprobe
  
  def add(self, vs):
    self.index.add(vs)

  def train(self, train_vectors):
    self.index.train(train_vectors) 

  def find(self, query, topn):
    D, I = self.index.search(query, topn) 
    return D, I

  def save(self,index):
    faiss.write_index(self.index, "flat.index")
    '''
    f = open(file, 'wb')
    pickle.dump(self.index, file)
    f.close()
    '''

  def load(self, file):
    self.index = faiss.read_index("file")
    '''
    f = open(file, 'rb')
    self.index = pickle.load(f)
    f.close()
    '''


In [ ]:
import numpy as np
import faiss

dim = 512
vectors = np.random.random((10000, dim)).astype('float32')


In [ ]:
vectors

array([[0.40567484, 0.24726497, 0.9929532 , ..., 0.58774656, 0.9164558 ,
        0.22228129],
       [0.5614106 , 0.23730758, 0.9968919 , ..., 0.08476409, 0.8451073 ,
        0.6197213 ],
       [0.93441767, 0.87079656, 0.42842066, ..., 0.9853476 , 0.89604324,
        0.8861582 ],
       ...,
       [0.10383826, 0.94795775, 0.43908018, ..., 0.3321783 , 0.1212099 ,
        0.8686052 ],
       [0.14488854, 0.13894224, 0.5508177 , ..., 0.9037032 , 0.07438311,
        0.35422388],
       [0.93421453, 0.7281983 , 0.9231372 , ..., 0.6554589 , 0.5960626 ,
        0.71071804]], dtype=float32)

In [ ]:
obj = FAISS_index(512)

In [ ]:
obj.train(vectors)

In [ ]:
obj.add(vectors)

In [ ]:
obj.find(vectors[0:1], 7)

(array([[ 0.     , 70.91014, 72.51279, 72.56651, 73.44196, 74.40196,
         74.40657]], dtype=float32),
 array([[     0, 684008, 692800,  93084, 229274, 607355, 437542]]))

In [ ]:
def test():
  assert obj.find(vectors[0:1], 1)[1][0] == 0


In [ ]:
test()